server:
  port: 8100
  servlet:
    context-path: /api/v1/
spring:
  application:
    name: auth
  #prod profile is active
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: ${POSTGRES_DB_PATH}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
  liquibase:
    changeLog: db/changelog/changelog-master.yaml
    enabled: true
  #jpa logs
  jpa:
    show-sql: true
    format-sql: true
  cache:
    type: none


access-token:
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
refresh-token:
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}

  #Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG

log4j:
  logger.httpclient.wire: DEBUG

#application variables
app:
  access-token:
    expiry-duration-min: ${APP_ACCESS_TOKEN_EXPIRY_DURATION_MIN}
  refresh-token:
    expiry-duration-days: ${APP_REFRESH_TOKEN_EXPIRY_DURATION_DAYS}
    min-renewal-days: ${APP_REFRESH_TOKEN_MIN_RENEWAL_DAYS}