
server:
  servlet:
    context-path: /api/v1/${spring.application.name}/
spring:
  application:
      name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/cr_dev_01
    username: postgres
    password: password
  liquibase:
    changeLog: db/changelog/changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true

logging:
  level:
    liquibase: info
    org:
      hibernate:
        sql: ERROR
        type: ERROR
        type.descriptor:
            sql: TRACE
      springframework:
        web:
          client:
            RestTemplate: DEBUG
log4J:
  logger:
    httpclient:
      wire: DEBUG


