server:
  port: 8100
  servlet:
    context-path: /api/v1/
spring:
  application:
    name: auth
  datasource:
    url: ${POSTGRES_DB_PATH}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
  liquibase:
    changeLog: db/changelog/changelog-master.yaml
    enabled: true
  #jpa logs
  jpa:
    show-sql: true
    format-sql: true
  cache:
    type: none
  #prod profile is active
  profiles:
    active: dev

access-token:
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
refresh-token:
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}

  #Logging
logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.web.client.RestTemplate: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

log4j:
    logger.httpclient.wire: DEBUG