
server:
  port: 8100
  servlet:
    context-path: /api/v1/${spring.application.name}/
spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/cr_dev_01
    username: postgres
    password: password
  liquibase:
    changeLog: db/changelog/changelog-master.yaml
    enabled: false
  jpa:
    show-sql: true

  #prod profile is active
  profiles:
    active: dev
