#server:
#  port: 8100
spring:
  application:
    name: auth
  profiles:
    active: dev

  datasource:
    url: ${POSTGRES_DB_PATH}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
  liquibase:
    changeLog: db/changelog/changelog-master.yaml
    enabled: true
  #jpa logs
  jpa:
    show-sql: true
    format-sql: true
  cache:
    type: none

  #Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG

log4j:
  logger.httpclient.wire: DEBUG


#application variables
#app:
#  key-pair:
#    directory: token-keys
#  access-token:
#    public-key-path: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
#    private-key-path: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
#    expiry-duration-min: ${APP_ACCESS_TOKEN_EXPIRY_DURATION_MIN}
#  refresh-token:
#    public-key-path: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
#    private-key-path: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
#    expiry-duration-days: ${APP_REFRESH_TOKEN_EXPIRY_DURATION_DAYS}
#    min-renewal-days: ${APP_REFRESH_TOKEN_MIN_RENEWAL_DAYS}