on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
run-name: Build by (${{ github.actor }}) Event - [${{ github.event_name }}]
name: Pull Request Checks
jobs:
 build:
   uses: ./.github/workflows/common.yml

