on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
run-name: Build by (${{ github.actor }}) Event - [${{ github.event_name }}]
name: Pull Request Checks
jobs:
 build:
   uses: ./.github/workflows/common.yml
   secrets: inherit
 example1:
   runs-on: ubuntu-latest
   needs:
     - test
     - security
     - analysis
   steps:
     - run: |
         echo "Running example1"
