on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
run-name: Build by (${{ github.actor }}) Event - [${{ github.event_name }}]
name: Pull Request Checks
jobs:
  test:
    uses: ./.github/workflows/reusable/test.yml
  analysis:
    uses: ./.github/workflows/reusable/analysis.yml
    secrets: inherit
