on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
run-name: Build by (${{ github.actor }}) Event - [${{ github.event_name }}]
name: Pull Request Checks
jobs:
  test:
    uses: ./.github/workflows/test.yml
  analysis:
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  example:
    runs-on: ubuntu-latest
    needs:
      - test
      - analysis
    steps:
      - run: |
          echo "example job here"
