name: ms-auth-ci
run-name: ${{ github.actor }} triggered the action
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '11'
      - name: run maven tests
        run: mvn clean test
