name: java-build-action
run-name: ${{ github.actor }} triggered the action
on: [push]
jobs:
  test-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '11'
           cache: 'maven'
      - name: run maven tests
        run: mvn clean test
