on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
jobs:
  deploy:
    name: Deployment in ${{inputs.environment-name}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deployment done in ${{inputs.environment-name}}"


