on:
  push:
    branches:
      - main
run-name: Deploy by (${{ github.actor }}) Event - [${{ github.event_name }}]
name: Deployment
jobs:
  build:
    steps:
      - uses: ./.github/workflows/test.yml
      - uses: ./.github/workflows/analysis.yml
        secrets: inherit

  tag-and-release:
    name: create release tag
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          release_branches: main
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  deploy:
    name: deploy in development, staging and uat environments
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "development not implemented yet"

