on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
jobs:
  deploy:
    name:  ${{inputs.environment-name}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "development not implemented yet"


