on:
  push:
    branches:
      - main
run-name: Publish by (${{ github.actor }}) Event - [${{ github.event_name }}]
name: Publish
jobs:
  analysis:
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    needs:
      - analysis

  release-tag:
    uses: ./.github/workflows/release-tag.yml
    needs:
      - test

  deployment:
    strategy:
      matrix:
        target: [ dev, sit, uat, prod ]
    uses: ./.github/workflows/deployment.yml
    with:
      target-environment: ${{ matrix.target }}
    needs:
      - release-tag

